server:
  port: 7002

eureka:
  instance:
    hostname: localhost

  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: false
    fetch-registry: false