server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**
        - id: payment_routh2
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
#            - After=2023-09-30T10:56:35.058+08:00[Asia/Shanghai]
#            - Cookie=username,lxb
#            - Header=X-Request-Id, \d+
#            - Host=**.atguigu.com
#            - Method=GET
#            - Query=username, \d+
          filters:
            - AddRequestParameter=X-Request-Id,1024
eureka:
  instance:
    hostname: cloud-gateway-service

  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: true
    fetch-registry: true